---
kind: secret
name: docker_username
get:
  path: my-drone-runner-docker-hub-secrets
  name: username
---
kind: secret
name: docker_password
get:
  path: my-drone-runner-docker-hub-secrets
  name: password
---
kind: pipeline
type: kubernetes
name: go
service_account_name: drone-runner
drone_namespace_default: drone-runner
metadata:
  namespoace: drone-runner

steps:
- name: init
  image: golang:1.20-alpine
  volumes:
  - name: deps
    path: /go  
  commands:
  - cd services/hello-world
  - go mod tidy
- name: test
  image: golang:1.20-alpine
  volumes:
  - name: deps
    path: /go  
  commands:
  - cd services/hello-world
  - go test -v ./...
  depends_on:
    - init 
- name: build
  image: golang:1.20-alpine
  volumes:
  - name: deps
    path: /go  
  commands:
  - cd services/hello-world
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./build/main ./cmd/main.go
  depends_on:
    - init
    - test
- name: containerize
  image: gcr.io/kaniko-project/executor:debug
  commands:
  - cd services/hello-world
  - /kaniko/executor --dockerfile Dockerfile --context . --no-push --destination=devopstester1234/hello-world-go:latest --destination=devopstester1234/hello-world-go:0.0.0-${DRONE_COMMIT} --tar-path=docker_image.tar
  depends_on:
    - build
- name: push-docker-image
  image: algreed/drone-load-and-store
  settings:
    archive: services/hello-world/docker_image.tar
    repo: devopstester1234/hello-world-go
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  depends_on:
    - containerize      
volumes:
- name: deps
  temp: {}    
